### ISSUE TITLE
No host described in new configuration 1 for replica set ( mongo replication )

### ISSUE THREAD

**Issue by schavalmane** [egymgmbh/kubernetes-web-mongo-sample#9]
We are trying to configure a mongo Replica ( 3 node ) on on Ipv6 only servers. And its failing with below error

> rs.initiate()
{
	"info2" : "no configuration explicitly specified -- making one",
	"me" : "XXX-01:27017",
	"ok" : 0,
	"errmsg" : "No host described in new configuration 1 for replica set RS1 maps to this node",
	"code" : 93
}

Config has below details on all nodes and we are not able to bringup mongo by assigning v6 IP to bindIp

net:
  port: 27017

  bindIp: 127.0.0.1  

#security:

security:
  keyFile: /mongo-keyfile
#operationProfiling:

#replication:

replication:
  replSetName: RS1

 3 nodes have the config defined as below

**Comment by llb4ll** [comment]
I think this is a problem with the IPv6 setup (see https://github.com/kubernetes/community/blob/master/contributors/design-proposals/networking.md#ipv6). IPv6 is not yet supported by kubernetes networking.
